name = "nusantara-hris"
main = "server.ts"
compatibility_date = "2026-08-01"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "hris_super_secure_jwt_secret_key_2026_hs256_cloud"
COMPANY_NAME = "PT Nusantara Digital Pratama"
WORK_START_TIME = "08:30"
WORK_END_TIME = "17:30"

[[d1_databases]]
binding = "DB"
database_name = "nusantara_hris_d1"
database_id = "d1-hris-prod-001"
migrations_dir = "./src/db/migrations"

[site]
bucket = "./public"
